import {
  defaultStrategy,
  emptyRule,
  type Condition,
  type Operand,
  type Strategy,
} from './strategy';
import type { IndicatorId } from './indicators';

const reddit = (id: string) =>
  `https://www.reddit.com/r/algotrading/comments/${id}/`;
export const STRATEGY_SOURCES = {
  averages: {
    title: 'Moving-average crossover discussion',
    url: reddit('1ov3g5r'),
  },
  rsi: { title: 'Connors RSI(4) mean-reversion rules', url: reddit('15qiymg') },
  bands: { title: 'Bollinger breakout backtest', url: reddit('1lka4qh') },
  donchian: {
    title: 'Donchian, SMA and ADX discussion',
    url: reddit('1s7eqm7'),
  },
  adx: { title: 'ADX backtest and failed variants', url: reddit('1irhrcw') },
  supertrend: {
    title: 'Supertrend and closed-bar signal timing',
    url: reddit('1e6kdrq'),
  },
  cloud: {
    title: 'Ichimoku trends and Bollinger ranges',
    url: reddit('gkcnod'),
  },
  cci: { title: 'CCI crossover backtest discussion', url: reddit('1k9zi45') },
  keltner: { title: 'Keltner breakout events', url: reddit('1q67agf') },
  indicators: {
    title: 'Indicator rule families and overfitting discussion',
    url: reddit('1b82n6u'),
  },
  macd: { title: 'ADX, MACD and RSI combinations', url: reddit('171h9aq') },
  momentum: { title: 'Momentum and volume indicators', url: reddit('1kumqhg') },
};
export type StrategyTemplate = {
  id: string;
  name: string;
  category: 'Trend' | 'Breakout' | 'Mean reversion' | 'Momentum' | 'Volume';
  entry: string;
  exit: string;
  adaptation: string;
  sources: (keyof typeof STRATEGY_SOURCES)[];
  strategy: Strategy;
};
const price: Operand = { kind: 'price', field: 'close' };
const n = (value: number): Operand => ({ kind: 'constant', value });
const i = (
  indicator: IndicatorId,
  period: number,
  plot?: string,
  offset?: number,
): Operand => ({ kind: 'indicator', indicator, period, plot, offset });
const c = (left: Operand, op: Condition['op'], right: Operand): Condition => ({
  left,
  op,
  right,
});
function template(
  id: string,
  name: string,
  category: StrategyTemplate['category'],
  entry: string,
  exit: string,
  enter: Condition[],
  leave: Condition[],
  sources: StrategyTemplate['sources'],
  adaptation = 'Replay defines these exact thresholds and exits from the discussed indicator family; this is not a reproduction of a published performance claim.',
): StrategyTemplate {
  return {
    id,
    name,
    category,
    entry,
    exit,
    sources,
    adaptation,
    strategy: {
      ...defaultStrategy(),
      name,
      longEntry: { join: 'and', conditions: enter },
      longExit: { join: 'or', conditions: leave },
      shortEntry: emptyRule(),
      shortExit: emptyRule(),
      allocationPct: 95,
      stopPct: undefined,
      targetPct: undefined,
      config: { initialCapital: 100000, commissionBps: 5, slippageBps: 5 },
    },
  };
}
const cross = (a: Operand, b: Operand) => [c(a, 'crossUp', b)];
const down = (a: Operand, b: Operand) => [c(a, 'crossDown', b)];
export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  template(
    'sma',
    'SMA crossover',
    'Trend',
    'SMA(20) crosses above SMA(50).',
    'SMA(20) crosses below SMA(50).',
    cross(i('sma', 20), i('sma', 50)),
    down(i('sma', 20), i('sma', 50)),
    ['averages'],
  ),
  template(
    'rsi',
    'RSI threshold',
    'Mean reversion',
    'RSI(14) is below 30.',
    'RSI(14) is above 70.',
    [c(i('rsi', 14), 'lt', n(30))],
    [c(i('rsi', 14), 'gt', n(70))],
    ['rsi'],
  ),
  template(
    'donchian',
    'Donchian breakout',
    'Breakout',
    'Close exceeds the previous 20-bar high.',
    'Close falls below the previous 10-bar low.',
    [c(price, 'gt', i('donchian', 20, 'upper', 1))],
    [c(price, 'lt', i('donchian', 10, 'lower', 1))],
    ['donchian'],
    'Simplified long-only channel system; no pyramiding, ATR sizing or Turtle skip rules. Channel levels exclude the signal candle.',
  ),
  template(
    'sma200',
    'Price above SMA 200',
    'Trend',
    'Close is above SMA(200).',
    'Close is below SMA(200).',
    [c(price, 'gt', i('sma', 200))],
    [c(price, 'lt', i('sma', 200))],
    ['averages'],
  ),
  template(
    'ema',
    'EMA crossover',
    'Trend',
    'EMA(12) crosses above EMA(26).',
    'EMA(12) crosses below EMA(26).',
    cross(i('ema', 12), i('ema', 26)),
    down(i('ema', 12), i('ema', 26)),
    ['averages'],
  ),
  template(
    'macd',
    'MACD signal crossover',
    'Momentum',
    'MACD(12,26) crosses above its 9-bar signal.',
    'MACD crosses below its signal.',
    cross(i('macd', 12, 'main'), i('macd', 12, 'signal')),
    down(i('macd', 12, 'main'), i('macd', 12, 'signal')),
    ['macd'],
  ),
  template(
    'adx',
    'ADX directional trend',
    'Trend',
    'ADX(14) > 25 and +DI crosses above −DI.',
    '+DI crosses below −DI.',
    [
      c(i('adx', 14, 'adx'), 'gt', n(25)),
      ...cross(i('adx', 14, 'plus-di'), i('adx', 14, 'minus-di')),
    ],
    down(i('adx', 14, 'plus-di'), i('adx', 14, 'minus-di')),
    ['adx'],
    'Uses the post’s directional entry; replaces its ATR stop/target with a reverse-DI signal exit. Costs included.',
  ),
  template(
    'ichimoku',
    'Ichimoku conversion / base',
    'Trend',
    '9-bar conversion crosses above 26-bar base.',
    'Conversion crosses below base.',
    cross(i('ichimoku', 9, 'conversion'), i('ichimoku', 9, 'base')),
    down(i('ichimoku', 9, 'conversion'), i('ichimoku', 9, 'base')),
    ['cloud'],
    'Conversion/base crossover only; no projected cloud or lagging-span confirmation.',
  ),
  template(
    'supertrend',
    'Supertrend reversal',
    'Trend',
    'Close crosses above Supertrend(10, multiplier 3).',
    'Close crosses below Supertrend.',
    cross(price, i('supertrend', 10)),
    down(price, i('supertrend', 10)),
    ['supertrend'],
  ),
  template(
    'psar',
    'Parabolic SAR reversal',
    'Trend',
    'Close crosses above SAR (step 0.02, cap 0.2).',
    'Close crosses below SAR.',
    cross(price, i('psar', 1)),
    down(price, i('psar', 1)),
    ['indicators'],
  ),
  template(
    'bb-breakout',
    'Bollinger momentum breakout',
    'Breakout',
    'Close crosses above the 20-bar upper band (2 standard deviations).',
    'Close falls below the 20-bar middle band.',
    cross(price, i('bbands', 20, 'upper')),
    [c(price, 'lt', i('bbands', 20, 'middle'))],
    ['bands'],
    'Daily long-only adaptation of the post’s intraday breakout family; uses a middle-band exit instead of reproducing its execution setup.',
  ),
  template(
    'bb-reversion',
    'Bollinger mean reversion',
    'Mean reversion',
    'Close is below the 20-bar lower band (2 standard deviations).',
    'Close is above the 20-bar middle band.',
    [c(price, 'lt', i('bbands', 20, 'lower'))],
    [c(price, 'gt', i('bbands', 20, 'middle'))],
    ['cloud'],
  ),
  template(
    'connors',
    'Connors RSI 4 pullback',
    'Mean reversion',
    'Close > SMA(200) and RSI(4) crosses below 30.',
    'RSI(4) crosses above 55.',
    [c(price, 'gt', i('sma', 200)), ...down(i('rsi', 4), n(30))],
    cross(i('rsi', 4), n(55)),
    ['rsi'],
    'Entry and exit thresholds follow the Reddit post; execution, sizing and costs use Replay assumptions.',
  ),
  template(
    'stochastic',
    'Stochastic oversold recovery',
    'Mean reversion',
    'Smoothed stochastic %K(14,3) crosses above 20.',
    '%K crosses above 80.',
    cross(i('stochastic', 14, 'main'), n(20)),
    cross(i('stochastic', 14, 'main'), n(80)),
    ['indicators'],
  ),
  template(
    'cci',
    'CCI trend impulse',
    'Momentum',
    'CCI(20) crosses above 100.',
    'CCI(20) crosses below zero.',
    cross(i('cci', 20), n(100)),
    down(i('cci', 20), n(0)),
    ['cci'],
    'CCI crossover family; Replay supplies thresholds and a zero-line exit instead of the post’s ATR stop and 3R target.',
  ),
  template(
    'williams',
    'Williams R recovery',
    'Mean reversion',
    'Williams %R(14) crosses above −80.',
    'Williams %R crosses above −20.',
    cross(i('williamsr', 14), n(-80)),
    cross(i('williamsr', 14), n(-20)),
    ['indicators'],
  ),
  template(
    'roc',
    'Rate-of-change momentum',
    'Momentum',
    '63-bar rate of change is positive.',
    '63-bar rate of change is negative.',
    [c(i('roc', 63), 'gt', n(0))],
    [c(i('roc', 63), 'lt', n(0))],
    ['momentum'],
  ),
  template(
    'cmf',
    'Chaikin money flow trend',
    'Volume',
    'CMF(20) > 0 and close > SMA(50).',
    'CMF(20) < 0 or close < SMA(50).',
    [c(i('cmf', 20), 'gt', n(0)), c(price, 'gt', i('sma', 50))],
    [c(i('cmf', 20), 'lt', n(0)), c(price, 'lt', i('sma', 50))],
    ['indicators', 'momentum'],
  ),
  template(
    'mfi',
    'Money flow oversold',
    'Volume',
    'MFI(14) is below 20.',
    'MFI(14) is above 80.',
    [c(i('mfi', 14), 'lt', n(20))],
    [c(i('mfi', 14), 'gt', n(80))],
    ['indicators'],
  ),
  template(
    'keltner',
    'Keltner channel breakout',
    'Breakout',
    'Close crosses above EMA(20) + 2 × Wilder ATR(20).',
    'Close falls below EMA(20).',
    cross(price, i('keltner', 20, 'upper')),
    [c(price, 'lt', i('keltner', 20, 'middle'))],
    ['keltner'],
  ),
  template(
    'aroon',
    'Aroon trend switch',
    'Trend',
    'Aroon up(25) crosses above Aroon down(25).',
    'Aroon up crosses below Aroon down.',
    cross(i('aroon', 25, 'main'), i('aroon', 25, 'signal')),
    down(i('aroon', 25, 'main'), i('aroon', 25, 'signal')),
    ['indicators'],
  ),
  template(
    'tsi',
    'True strength momentum',
    'Momentum',
    'TSI(25,13) crosses above zero.',
    'TSI crosses below zero.',
    cross(i('tsi', 25), n(0)),
    down(i('tsi', 25), n(0)),
    ['indicators'],
  ),
  template(
    'ultimate',
    'Ultimate oscillator recovery',
    'Mean reversion',
    'Ultimate oscillator(7,14,28) crosses above 30.',
    'Ultimate oscillator crosses above 70.',
    cross(i('ultimate', 7), n(30)),
    cross(i('ultimate', 7), n(70)),
    ['indicators'],
  ),
  template(
    'stochrsi',
    'Stochastic RSI pullback',
    'Mean reversion',
    'StochRSI(14,3,3) %K crosses above 20 while close > SMA(200).',
    'StochRSI %K crosses above 80 or close < SMA(200).',
    [...cross(i('stochrsi', 14, 'main'), n(20)), c(price, 'gt', i('sma', 200))],
    [...cross(i('stochrsi', 14, 'main'), n(80)), c(price, 'lt', i('sma', 200))],
    ['indicators', 'macd'],
  ),
];
